### ISSUE TITLE
Read Console Properties from config.json file

### ISSUE THREAD

**Issue by mfriesen** [formkiq/formkiq-console#34]
Read config.json file for Console properties. Current Format is:
{
  "cognito": {
    "userPoolId": "us-east-XXXXXXXXXX",
    "region": "us-east-1",
    "clientId": "XXXXXXXXXXXXXXXXXXXXX"
  },"apigateway": {
    "url": "https://XXXXXXXX.execute-api.us-east-1.amazonaws.com/test/"
  }
}

**Comment by reganwolfrom** [comment]
This file exists at /assets/config.json, so build puts in /dist/assets/config.json.

**Comment by reganwolfrom** [comment]
Config may be getting compiled and not loaded at run-time. Need to investigate.

**Comment by reganwolfrom** [comment]
Possible solution: https://robinraju.dev/developer/2017-11-14-loading-external-config-in-angular/

**Comment by reganwolfrom** [comment]
Or: https://davembush.github.io/where-to-store-angular-configurations/
