### ISSUE TITLE
WIP: Reset Password Errors

### ISSUE THREAD

**Issue by mfriesen** [formkiq/formkiq-console#57]
If the Email doesn't exist.. get error message "Username/client id combination not found" .. Not sure if we want to change this to "Email address not found" or send normal reset password link.

Also if userstatus is FORCE_CHANGE_PASSWORD .. cannot reset password .. get error User password cannot be reset in the current state.

**Comment by reganwolfrom** [comment]
@mfriesen I'm not sure how to get userstatus to FORCE_CHANGE_PASSWORD, but when userstatus is RESET_REQUIRED, I received the following exception:

CustomMessage failed with error null. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: UserLambdaValidationException; Request ID: 106a2c2f-79be-4f16-96e0-519afdcf5ee4)

Can you either give me steps to create FORCE_CHANGE_PASSWORD or set the status of one of my test users to that state?

Thanks!

**Comment by mfriesen** [comment]
It's been added to my list https://github.com/formkiq/formkiq-cloud/issues/105

**Comment by reganwolfrom** [comment]
I think that might one and the same status, then, so once you error is
gone, I can finish up this one.

**Comment by mfriesen** [comment]
I think this Ticket is complete.
