### ISSUE TITLE
Show Document Listing Header when no results

### ISSUE THREAD

**Issue by mfriesen** [formkiq/formkiq-console#75]
Right now if you have no documents the search page looks weird without the header show. Should just looks like if no documents are found.

Also should show the Date Inserted with a Timezone attached IE: -0800.

**Comment by mfriesen** [comment]
<img width="1482" alt="Screen Shot 2020-03-20 at 1 44 12 PM" src="https://user-images.githubusercontent.com/250329/77196460-64bbb400-6ab1-11ea-8acd-6e1f2c46f25c.png">

**Comment by reganwolfrom** [comment]
I think we'd be better off defaulting to today's date, since once you run once search, it saves that search for next load. Otherwise I'm adding a bunch of conditional display code that shows up for a user once in their lives. Thoughts?
