### ISSUE TITLE
SignUp Change Password

### ISSUE THREAD

**Issue by mfriesen** [formkiq/formkiq-console#82]
After signing up, you need to reset your password. But if you enter a password that doesn't meet the password critieria, you get sent back to the login page and not the change password page.

**Comment by mfriesen** [comment]
<img width="620" alt="Screen Shot 2020-03-21 at 9 54 10 PM" src="https://user-images.githubusercontent.com/250329/77241342-b867f380-6bbe-11ea-93f6-34cb1621b8b2.png">

**Comment by reganwolfrom** [comment]
Which account did you try? Were there special characters (like '+') in the email?

The reset email isn't providing a URL to click, when it should be providing one (with url encoded username).

Example:
http://localhost:4200/resetPassword?user_name=regan.wolfrom%2Btest3@gmail.com&code=683062

I've just added client-side code to detect if username is not valid and to notify, but with a valid username this flow _should_ be working.

@mfriesen I'll check in, and we'll see if you can still break on retry. Thanks!

**Comment by reganwolfrom** [comment]
Re-opened pending re-test verification
