### ISSUE TITLE
Increase Share link life to 48 hours by default

### ISSUE THREAD

**Issue by reganwolfrom** [formkiq/formkiq-console#88]
Currently, share action creates a CloudFront link that lasts for one hour. This should be extended to 48 hours for now, with future customization to come.

**Comment by mfriesen** [comment]
https://github.com/formkiq/formkiq-cloud/issues/129 
Changed default to 48 hours.

**Comment by reganwolfrom** [comment]
Handled by FormKiQ Cloud change
